name: CI

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      shell: bash
      run: |
        echo "TIER_TEST" > tier.txt
        ./build.sh build start
      env:
        fail-fast: true

    - name: Run tests
      shell: bash
      run: |
        ./build.sh test

