name: CI

on: [pull_request]

jobs:

  build-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create keymanapi Database
      shell: cmd
      run: |
        "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" create keymanapi
        "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" start keymanapi
    - name: Install dependencies
      shell: cmd
      run: |
        composer install
    - name: Build keymanapi database
      shell: cmd
      run: |
        call .github\workflows\prepenv.cmd
        type tools\db\localenv.php
        php tools\db\build\build_cli.php
    - name: Run unit tests
      shell: cmd
      run: |
        vendor\bin\phpunit tests
