name: CI

on: [pull_request]

jobs:

  build-test:
    runs-on: windows-latest
    env:
      api_keyman_com_mssql_pw:
      api_keyman_com_mssql_user:
      api_keyman_com_mssqlconninfo: sqlsrv:Server=(localdb)\keymanapi;Database=
      api_keyman_com_mssqlconninfo_master: sqlsrv:Server=(localdb)\keymanapi;Database=master
      api_keyman_com_mssqldb0: keyboards
      api_keyman_com_mssqldb1: keyboards_1
      api_keyman_com_keyboard_info_zip: https://downloads.keyman.com/data/keyboard_info.zip
      api_keyman_com_model_info_zip: https://downloads.keyman.com/data/model_info.zip

    steps:
    - uses: actions/checkout@v2
    - name: Create keymanapi Database
      shell: cmd
      run: |
        "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" create keymanapi
        "C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe" start keymanapi
    - name:  Install dependencies
      shell: cmd
      run:   composer install --no-progress
    - name:  Install PHP mssql PDO Driver
      shell: powershell
      run: |
        Invoke-WebRequest -outfile pdo.zip https://github.com/microsoft/msphpsql/releases/download/v5.8.0/Windows-7.4.zip
        Expand-Archive pdo.zip -DestinationPath pdo\
        copy pdo\Windows-7.4\x64\php_pdo_sqlsrv_74_nts.dll c:\tools\php\ext\
        Add-Content -path c:\tools\php\php.ini -value '','extension=php_pdo_sqlsrv_74_nts.dll','mssql.secure_connection=Off'
    - name:  Build keymanapi database
      shell: cmd
      run:   php tools\db\build\build_cli.php
    - name:  Run unit tests
      shell: cmd
      run:   vendor\bin\phpunit tests
